package com.capitalone.identity.identitybuilder.policycore.dmnrules;

import com.capitalone.identity.identitybuilder.policycore.camel.PolicyConstants;
import com.capitalone.identity.identitybuilder.policycore.decisionengine.DecisionResult;
import com.newrelic.api.agent.Trace;
import org.apache.camel.Exchange;
import org.apache.camel.Message;
import org.apache.camel.Processor;

import java.util.Collections;
import java.util.List;

/**
 * <p>Processor that sets message body to list of decision engine results,
 * individually generated by {@link DMNRulesProcessor}, that are stored in {@link PolicyConstants#POLICY_RULE_RESULTS}
 * header.</p>
 * <br>
 * <h3>The following headers are expected in camel exchange:</h3>
 * <ul>
 * <li>
 * {@link PolicyConstants#POLICY_RULE_RESULTS}: list of {@link DecisionResult} objects);
 * </li>
 * </ul>
 */
public class DMNRulesCollectProcessor implements Processor {

    @SuppressWarnings("unchecked")
	@Override
    @Trace
    public void process(Exchange exchange) throws Exception {
        Message msg = exchange.getIn();
        List<DecisionResult> rulesDecisionResult = (List<DecisionResult>) msg.getHeader(PolicyConstants.POLICY_RULE_RESULTS, Collections.emptyList());
        exchange.getMessage().setBody(rulesDecisionResult);

    }

}
